### ISSUE TITLE
IP Address issue

### ISSUE THREAD

**Issue by DavidFrahmVS** [Shellntel/scripts#8]
Tried to run the script on Ubuntu 16.04 on VMWare, and got the following error:
proxyadmin@VIVCOPROXCAN02:~/scripts$ python proxyCannon.py 5
Traceback (most recent call last):
  File "proxyCannon.py", line 604, in <module>
    localIP = get_ip_address(args.interface)
  File "proxyCannon.py", line 590, in get_ip_address
    struct.pack('256s', ifname[:15])
IOError: [Errno 19] No such device

**Comment by i128** [comment]
What are the names of your interfaces on the device? By default proxy cannon will look for eth0 for all outbound connections. If you use something else, you can specify which interface you'd like it to use using the:  -i <interface name> or --interface <interface name>

**Comment by DavidFrahmVS** [comment]
Perfect! That seems to have done it!

David Frahm
